blank_issues_enabled: true
contact_links:
    - name: â“ Ask a question
      url: https://github.com/trufaco/kazza-roadmap/discussions/new
      about: We use GitHub issues for Bugs & New Feature Requests. For support, please use Discussions!
    - name: ğŸ“š Wiki
      url: https://github.com/trufaco/kazza-roadmap/wiki
      about: Kazza documentation at your fingertips
